import type { IGuideLink, TLinkAccess } from '../types';

/** Проверенные ссылки курса (документ «Импрува — курс годового челленджа», раздел «Библиотека»). */
const link = (title: string, url: string, access: TLinkAccess, locator = ''): IGuideLink => ({ title, url, locator, access });

const COMMONS = 'https://commons.wikimedia.org/wiki/Category:';

export const L = {
  drawabox0: link('Drawabox, урок 0', 'https://drawabox.com/lesson/0', 'free', 'Getting Started'),
  drawabox1: link('Drawabox, урок 1', 'https://drawabox.com/lesson/1', 'free', 'Lines, Ellipses and Boxes'),
  drawabox2: link('Drawabox, урок 2', 'https://drawabox.com/lesson/2', 'free', 'Contour Lines, Texture and Construction'),
  drawabox250: link('250 Box Challenge', 'https://drawabox.com/lesson/250boxes', 'free'),
  speed: link('Speed — The Practice and Science of Drawing', 'https://www.gutenberg.org/ebooks/14264', 'pd'),
  bridgman: link('Bridgman — Constructive Anatomy, PDF', 'https://archive.org/details/cu31924014504371', 'pd'),
  vanderpoel: link('Vanderpoel — The Human Figure, PDF', 'https://archive.org/details/humanfigure00vanduoft', 'pd'),
  norton: link('Norton — Freehand Perspective and Sketching, PDF', 'https://archive.org/details/freehandperspect00nortrich', 'pd'),
  storey: link('Storey — The Theory and Practice of Perspective', 'https://www.gutenberg.org/ebooks/20165', 'pd'),
  ruskinDrawing: link('Ruskin — The Elements of Drawing', 'https://www.gutenberg.org/files/30325/30325-h/30325-h.htm', 'pd'),
  leonardoNotes: link('Леонардо — The Notebooks', 'https://www.gutenberg.org/ebooks/5000', 'pd'),
  bargue: link('Листы курса Барга, часть I', `${COMMONS}Bargue-G%C3%A9r%C3%B4me_Drawing_Course_I`, 'pd'),
  proko: link('Proko — How to Draw Gesture', 'https://www.proko.com/course-lesson/how-to-draw-gesture', 'free'),
  loa: link('Line of Action — наброски по таймеру', 'https://line-of-action.com/practice-tools/app/figure-drawing', 'free'),
  ctrlLibrary: link('Ctrl+Paint — бесплатная библиотека', 'https://www.ctrlpaint.com/library', 'free'),
  ctrlPerspective: link('Ctrl+Paint — Basic Perspective', 'https://www.ctrlpaint.com/videos/perspective', 'free'),
  ctrlValue: link('Ctrl+Paint — Sketching: Value', 'https://www.ctrlpaint.com/videos/sketching-value', 'free'),
  bucci: link('Marco Bucci — 10 Minutes to Better Painting', 'https://www.youtube.com/playlist?list=PL2MPJVby8-FVNcT35aKv6Ha30lwVYyK8G', 'free'),
  gurneyForm: link('Gurney — Light and Form, Part 1', 'https://gurneyjourney.blogspot.com/2010/02/light-and-form-part-1_15.html', 'free'),
  gurneyGamut: link('Gurney — Gamut Masking, Part 1', 'https://gurneyjourney.blogspot.com/2011/09/part-1-gamut-masking-method.html', 'free'),
  gurneySpeed: link('Gurney — Harold Speed on Painting', 'http://gurneyjourney.blogspot.com/2015/11/harold-speed-on-painting-preface-and.html', 'free'),
  gurneyBook: link('Gurney — Color and Light', 'https://publishing.andrewsmcmeel.com/book/color-and-light/', 'paid'),
  munsell: link('Munsell Color Science for Painters', 'https://www.munsellcolorscienceforpainters.com/MunsellSystem/MunsellSystem.html', 'free'),
  zornChart: link('Сетка палитры Цорна', 'https://www.artistsandillustrators.co.uk/how-to/art-theory/how-to-make-a-colour-chart-using-the-zorn-palette/', 'free'),
  willKemp: link('Will Kemp — бесплатные видео по акрилу', 'https://willkempartschool.com/acrylic-painting-tutorial-videos/', 'free'),
  gamblinSolventFree: link('Gamblin — Solvent-Free Painting', 'https://gamblincolors.com/solvent-free-painting/', 'free'),
  gamblinFatOverLean: link('Gamblin — Fat-Over-Lean', 'https://gamblincolors.com/fat-over-lean/', 'free'),
  baumanSightSize: link('Stephen Bauman — фигура методом sight-size', 'https://www.youtube.com/watch?v=k0uocfnA4f8', 'free'),
  baumanChannel: link('Stephen Bauman — канал', 'https://www.youtube.com/channel/UCqEWLv392F0J9rN7jE1-f3w', 'free'),
  usk: link('Urban Sketchers — манифест', 'https://urbansketchers.org/2009/06/16/statement-of-purpose/', 'free'),
  met: link('Met Open Access', 'https://www.metmuseum.org/art/collection/search?showOnly=openAccess', 'free'),
  nga: link('National Gallery of Art — открытые изображения', 'https://www.nga.gov/artworks/free-images-and-open-access', 'free'),
  wga: link('Web Gallery of Art', 'https://www.wga.hu/', 'free'),
  artCamera: link('Google Arts & Culture — Art Camera', 'https://artsandculture.google.com/project/art-camera', 'free'),
  li: link('Н. Ли — Основы учебного академического рисунка', 'https://eksmo.ru/book/risunok-osnovy-uchebnogo-akademicheskogo-risunka-4305127/', 'paid'),
  robertson: link('Robertson — How to Draw', 'https://designstudiopress.com/products/how-to-draw', 'paid'),
  robertsonVideos: link('How to Draw — видео к главам', 'https://scottrobertsonworkshops.com/h2dr/', 'free'),
  framedInk: link('Mateu-Mestre — Framed Ink', 'https://designstudiopress.com/products/framed-ink', 'paid'),
  ching: link('Ching — Architecture: Form, Space, and Order', 'https://www.wiley.com/en-us/Architecture:+Form,+Space,+and+Order,+5th+Edition-p-9781119853381', 'paid'),
  schmid: link('Schmid — Alla Prima II', 'https://www.richardschmid.com/Alla-Prima-II-By-Richard-Schmid-p/skuap.htm', 'paid'),
  zornPaintings: link('Цорн — живопись', `${COMMONS}Paintings_by_Anders_Zorn`, 'pd'),
  zornEtchings: link('Цорн — офорты', `${COMMONS}Etchings_by_Anders_Zorn`, 'pd'),
  sorolla: link('Соролья — живопись', `${COMMONS}Paintings_by_Joaqu%C3%ADn_Sorolla`, 'pd'),
  sargentPaintings: link('Сарджент — живопись', `${COMMONS}Paintings_by_John_Singer_Sargent`, 'pd'),
  sargentDrawings: link('Сарджент — рисунки', `${COMMONS}Drawings_by_John_Singer_Sargent`, 'pd'),
  repin: link('Репин — живопись', `${COMMONS}Paintings_by_Ilya_Yefimovich_Repin`, 'pd'),
  serov: link('Серов', `${COMMONS}Valentin_Serov`, 'pd'),
  serovDrawings: link('Серов — рисунки', `${COMMONS}Drawings_by_Valentin_Serov`, 'pd'),
  levitan: link('Левитан — живопись', `${COMMONS}Paintings_by_Isaac_Levitan`, 'pd'),
  shishkin: link('Шишкин', `${COMMONS}Ivan_Shishkin`, 'pd'),
  rembrandt: link('Рембрандт — рисунки', `${COMMONS}Drawings_by_Rembrandt`, 'pd'),
  fechinPaintings: link('Фешин — живопись', `${COMMONS}Paintings_by_Nikolai_Fechin`, 'pd'),
  fechinDrawings: link('Фешин — рисунки', `${COMMONS}Drawings_by_Nikolai_Fechin`, 'pd'),
  durer: link('Дюрер — рисунки', `${COMMONS}Drawings_by_Albrecht_D%C3%BCrer`, 'pd'),
  holbein: link('Гольбейн — портретные рисунки', `${COMMONS}Portrait_drawings_by_Hans_Holbein_der_J%C3%BCngere`, 'pd'),
  degas: link('Дега — живопись', `${COMMONS}Paintings_by_Edgar_Degas`, 'pd'),
  monet: link('Моне — живопись', `${COMMONS}Paintings_by_Claude_Monet`, 'pd'),
  turner: link('Тёрнер — акварели', `${COMMONS}Watercolor_paintings_by_Joseph_Mallord_William_Turner`, 'pd'),
  hokusai: link('Хокусай — гравюры', `${COMMONS}Ukiyo-e_prints_by_Katsushika_Hokusai`, 'pd'),
} as const;
